; Script generated by the HM NIS Edit Script Wizard.

; nsProcessKiller
!include "nsProcessKiller.nsh"

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "test"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "r00tdr4g0n"
!define PRODUCT_WEB_SITE "blog.naver.com/0k00k0"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Language files
!insertmacro MUI_LANGUAGE "Korean"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\test"
ShowInstDetails show

Section "MainSection" SEC01
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateDirectory "$SMPROGRAMS\test"
  CreateShortCut "$SMPROGRAMS\test\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
SectionEnd

Section -Post
SectionEnd

Var target
Var pid

Function .onInit
  StrCpy $target "TargetDll.dll"
  ${nsProcessKiller::FindProcessUsingDll} $target
  Pop $pid
  MessageBox MB_OKCANCEL "Are you sure you want to quit $target(pid:$pid)?" IDCANCEL end
  ${nsProcessKiller::KillProcess} $pid
  end:
FunctionEnd